### ISSUE TITLE
how to get background images

### ISSUE THREAD

**Issue by andyjiang1116** [tzm-tora/Stroke-Based-Scene-Text-Erasing#10]
I want to know what background images are used in training, could you share it?

**Comment by tzm-tora** [comment]
hi, we randomly cropped the background patches from two background sets. One is the same as the SynthText dataset, another is the Describable Textures Dataset.

**Comment by andyjiang1116** [comment]
OK, thanks a lot. But I'm confused of the following question
1. What size of cropped background images are used for training? 
2. Why used 128x640 image shape for training? As we can know, most text recognition images are 32x320 or 48x256. So big image shape will help improve the performance?

**Comment by tzm-tora** [comment]
hi, 
1. the size of cropped background images is according to the size of text to render. the size of text is random in a predefined range in Pygame library. This range is decided according to the image size we used.
2. We used the 128x640 image for training because we initially wanted to bulid a general practical text erasing method, not only for the evluation on SCUT-EnsText dataset. We think 128x640 is a relatively safe size both for general inference and training. And we have tried other patch sizes, so we cannot give a answer about the performance degradation or improvement.

**Comment by andyjiang1116** [comment]
thanks for your patient answer,  I found the model can receive different shape for training without changing anything about the model file, so if I want to training my own model in a small shape, eg: 32x320, will I get an efficient model? or should I change something for the model file?

**Comment by tzm-tora** [comment]
You are welcome, I cannot promise there is no bug if you change the image shape, but I think you can try and then debug.
